import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const readSource = (path) => fs.readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8');

const PUBLIC_COPY_FILES = [
  'src/features/home/HomeHeroStage.tsx',
  'src/features/home/home-view-helpers.ts',
  'src/features/home/server/loadHomePageData.ts',
  'src/features/home/server/home-feed-loader.ts',
  'src/features/home/server/home-feed-shared.ts',
  'src/app/movies/MoviesPageClient.tsx',
  'src/app/series/SeriesPageClient.tsx',
  'src/features/comics/ComicPageClient.tsx',
  'src/components/organisms/MediaHubTemplate.tsx',
  'src/app/movies/[slug]/page.tsx',
  'src/app/movies/[slug]/movie-playback-state.ts',
  'src/app/series/[slug]/page.tsx',
  'src/app/series/[slug]/SeriesEpisodeSection.tsx',
  'src/features/comics/ComicTitlePage.tsx',
  'src/features/comics/ComicChapterPage.tsx',
  'src/features/auth/AuthPageShell.tsx',
  'src/features/auth/LoginPage.tsx',
  'src/features/auth/SignupPage.tsx',
  'src/components/organisms/FooterContent.tsx',
  'src/lib/media-hub-segments.ts',
  'src/components/organisms/SearchModal.tsx',
  'src/features/community/TitleCommunityPanel.tsx',
  'src/features/community/UnitCommunityPanel.tsx',
  'src/features/community/community-panel-shared.tsx',
  'src/components/molecules/CommunityCTA.tsx',
  'src/components/organisms/ContinueWatching.tsx',
  'src/components/organisms/SavedContentSection.tsx',
  'src/components/organisms/MediaDownloadOptionsPanel.tsx',
  'src/lib/video-player-controls.ts',
  'src/components/organisms/video-player/VideoPlayerMirrorPanel.tsx',
  'src/components/organisms/WatchRails.tsx',
  'src/components/atoms/ReaderPageImage.tsx',
  'src/features/shorts/DrachinPageClient.tsx',
  'src/features/shorts/DrachinDetailClient.tsx',
  'src/features/shorts/DrachinEpisodeClient.tsx',
  'src/components/organisms/SectionCard.tsx',
  'src/components/organisms/BookmarkButton.tsx',
  'src/app/vault/page.tsx',
  'src/app/vault/history/page.tsx',
  'src/app/vault/saved/page.tsx',
  'src/app/vault/profile/page.tsx',
  'src/app/account/age/page.tsx',
  'src/app/onboarding/OnboardingWizard.tsx',
  'src/app/onboarding/steps/IdentityStep.tsx',
  'src/app/onboarding/steps/AgeAccessStep.tsx',
  'src/app/onboarding/steps/MediaPreferencesStep.tsx',
  'src/app/onboarding/steps/TasteSeedsStep.tsx',
  'src/app/onboarding/steps/OptInsStep.tsx',
  'src/lib/home-curation.ts',
  'src/components/organisms/MediaWatchPage.tsx',
  'src/lib/shorts-paths.ts',
  'src/app/search/SearchResultsPageClient.tsx',
  'src/lib/search/search-contract.ts',
  'src/lib/navigation.ts',
  'src/components/organisms/Navbar.tsx',
  'src/components/organisms/MobileNav.tsx',
  'src/components/organisms/MobileMenuPanel.tsx',
  'src/components/organisms/AuthNavEntry.tsx',
  'src/components/organisms/AuthMobileEntry.tsx',
  'src/components/molecules/ReadingSettings.tsx',
  'src/components/molecules/PWAInstallPrompt.tsx',
  'src/features/series/SeriesEpisodePage.tsx',
  'src/app/read/comics/page.tsx',
];

const LEGACY_COPY_PATTERNS = [
  /Cinematic pick/,
  /Featured movie/,
  /Featured series/,
  /Featured comic/,
  /Feature film spotlight/,
  /Episodic spotlight/,
  /Movie Hub/,
  /Series Hub/,
  /Comic Library/,
  /Movie browse/,
  /Series browse/,
  /Comic browse/,
  /Browse By Shelf/,
  /Browse By Type/,
  /Watch Now/,
  /Read Now/,
  /Open Stream/,
  /Playback Unavailable/,
  /Browse Movies/,
  /Browse Series/,
  /Browse Comics/,
  /Start watching/,
  /Start reading/,
  /View detail/,
  /Continue browsing/,
  /Clear filter/,
  /Search Error/,
  /No Content Found/,
  /No Comics Found/,
  /personal lane/,
  /watch lanes/,
  /reading shelf/,
  /canonical (?:comic|episodic|list|metadata|surface|series|catalog|database|comic hub)/i,
  /one .*shell/i,
  /Open lane/,
  /Continue with Google/,
  /Continue with Discord/,
  /Continue with password/,
  /Create account/,
  /Forgot password/,
  /Terms of Service/,
  /Privacy Policy/,
  /Search media/,
  /Search titles across watch and read/,
  /Top Match/,
  /No matches found/,
  /Quick Keys/,
  /Press Enter to see all results/,
  /Watch Options/,
  /Auto Play/,
  /Next episode/,
  /Report mirror/,
  /Refresh player/,
  /Toggle lights/,
  /Toggle theater mode/,
  /Series rail/,
  /Episode navigation/,
  /Default mode keeps/,
  /Quick jump/,
  /Related rail/,
  /Watch next/,
  /Image unavailable/,
  /Open source/,
  /Join Community/,
  /Talk about/,
  /Local-first community/,
  /Like this unit/,
  /Continue in Discord/,
  /Post Comment/,
  /Post Reply/,
  /No synced/,
  /No local/,
  /Community around/,
  /Community follows/,
  /Open unit/,
  /No activity yet/,
  /Download Options/,
  /Saved items start locally/,
  /Local saved shelf/,
  /View Full History/,
  /Watch:/,
  /Read:/,
  /Watch Movies/,
  /Watch Series/,
  /Watch Shorts/,
  /external .* feed/,
  /Featured Stories/,
  /Latest Episodes/,
  /Popular Stories/,
  /Immersive Feed/,
  /Story detail unavailable/,
  /Vertical Series/,
  /Episode Guide/,
  /Now Watching/,
  /Short Hub/,
  /Watch Hub/,
  /Auto-next ready/,
  /Story Page/,
  /Quick Queue/,
  /Play Next Now/,
  /Stay Here/,
  /Continue Scrolling/,
  /Jump to Next/,
  /Birth Date/,
  /Save Settings/,
  /Step \{stepIndex \+ 1\} of/,
  /Optional Step/,
  /Required Step/,
  /Media Preferences/,
  /Taste Seeds/,
  /Finish Onboarding/,
  /Search Hub/,
  /Canonical Search/,
  /Grouped Results/,
  /Search Titles/,
  /Type something to search/,
  /Searching titles/,
  /Title-first discovery/,
  /Sign in for bookmark/,
  /Signed in with/,
  />Logout</,
  /Account settings/,
  /Coming later/,
  /Cinematic watch/,
  /Open search/,
  /Read Comics/,
  /reading hub/,
  /Reader Settings/,
  /Container Width/,
  /Install App/,
  /Install jawatch/,
  /Dismiss install/,
  /System default/,
  /Identity and access/,
  /Profile preferences/,
  /Manage age/,
  /Save preferences/,
  /Series detail/,
  /More series/,
  /Episode context/,
  /Inline ready/,
  /Open menu/,
];

test('public UX copy avoids legacy English and internal product jargon', () => {
  for (const file of PUBLIC_COPY_FILES) {
    const source = readSource(file);

    for (const pattern of LEGACY_COPY_PATTERNS) {
      assert.doesNotMatch(source, pattern, `${file} still contains ${pattern}`);
    }
  }
});

test('public UX copy keeps Indonesian marketplace-style action labels', () => {
  const homeHero = readSource('src/features/home/HomeHeroStage.tsx');
  assert.match(homeHero, /Pilihan buat kamu/);
  assert.match(homeHero, /Mulai nonton/);
  assert.match(homeHero, /Lihat dulu/);

  const movies = readSource('src/app/movies/MoviesPageClient.tsx');
  assert.match(movies, /Nonton sekarang/);
  assert.match(movies, /Lihat detail/);
  assert.match(movies, /Pilih rak film/);

  const series = readSource('src/app/series/SeriesPageClient.tsx');
  assert.match(series, /Lanjut nonton/);
  assert.match(series, /Pilih rak series/);

  const comics = readSource('src/features/comics/ComicPageClient.tsx');
  assert.match(comics, /Baca sekarang/);
  assert.match(comics, /Simpan ke rak/);
  assert.match(comics, /Pilih rak komik/);
});
